version: '3.3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    restart: always

  mongo:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=anyuser
      - MONGODB_ROOT_PASSWORD=anypassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-db:/bitnami/mongodb'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    #TODO: Secure env variables
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: anyuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: anypassword
      ME_CONFIG_MONGODB_URL: mongodb://anyuser:anypassword@mongo:27017/trimm?authSource=admin
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
volumes:
  mongo-db: